# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/onda/andy/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/onda/andy/proprietary/lib/libaudio.so:obj/lib/libaudio.so

PRODUCT_COPY_FILES += \
    vendor/onda/andy/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/onda/andy/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/onda/andy/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/onda/andy/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/onda/andy/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/onda/andy/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/onda/andy/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/onda/andy/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/onda/andy/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/onda/andy/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/onda/andy/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/onda/andy/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/onda/andy/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/onda/andy/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/onda/andy/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/onda/andy/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/onda/andy/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/onda/andy/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/onda/andy/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/onda/andy/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/onda/andy/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/onda/andy/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/onda/andy/proprietary/lib/libsnd.so:system/lib/libsnd.so \
    vendor/onda/andy/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/onda/andy/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/onda/andy/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/onda/andy/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/onda/andy/proprietary/bin/rild:system/bin/rild \
    vendor/onda/andy/proprietary/bin/CKPD-daemon:system/bin/CKPD-daemon \
    vendor/onda/andy/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/onda/andy/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    vendor/onda/andy/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/onda/andy/proprietary/lib/hw/sensors.msm7k.so:system/lib/hw/sensors.msm7k.so \
    vendor/onda/andy/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/onda/andy/proprietary/lib/hw/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/onda/andy/proprietary/lib/hw/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/onda/andy/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/onda/andy/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/onda/andy/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/onda/andy/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/onda/andy/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/onda/andy/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/onda/andy/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/onda/andy/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/onda/andy/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/onda/andy/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/onda/andy/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/onda/andy/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/onda/andy/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/onda/andy/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/onda/andy/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/onda/andy/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/onda/andy/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/onda/andy/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/onda/andy/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/onda/andy/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/onda/andy/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/onda/andy/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/onda/andy/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/onda/andy/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/onda/andy/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/onda/andy/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/onda/andy/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/onda/andy/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/onda/andy/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/onda/andy/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/onda/andy/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/onda/andy/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/onda/andy/proprietary/etc/bt_fw.hcd:system/etc/bt_fw.hcd \
    vendor/onda/andy/proprietary/etc/bcm4329.ko:system/etc/bcm4329.ko \
    vendor/onda/andy/proprietary/etc/rtecdc_ap.bin:system/etc/rtecdc_ap.bin \
    vendor/onda/andy/proprietary/etc/rtecdc.bin:system/etc/rtecdc.bin \
    vendor/onda/andy/proprietary/bin/battery_charging:system/bin/battery_charging \
    vendor/onda/andy/proprietary/bin/cciclean:system/bin/cciclean \
    vendor/onda/andy/proprietary/bin/ccidag:system/bin/ccidag \
    vendor/onda/andy/proprietary/bin/ccihwid:system/bin/ccihwid \
    vendor/onda/andy/proprietary/bin/cci-props:system/bin/cci-props \
    vendor/onda/andy/proprietary/bin/cnd:system/bin/cnd \
    vendor/onda/andy/proprietary/bin/diag_klog:system/bin/diag_klog \
    vendor/onda/andy/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
    vendor/onda/andy/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/onda/andy/proprietary/bin/fmfc:system/bin/fmfc \
    vendor/onda/andy/proprietary/bin/fmsvc:system/bin/fmsvc \
    vendor/onda/andy/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/onda/andy/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/onda/andy/proprietary/bin/hostapd_cli:system/bin/hostapd_cli \
    vendor/onda/andy/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/onda/andy/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/onda/andy/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/onda/andy/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/onda/andy/proprietary/bin/usbhub:system/bin/usbhub \
    vendor/onda/andy/proprietary/bin/usbhub_init:system/bin/usbhub_init \
    vendor/onda/andy/proprietary/bin/wlan_addr:system/bin/wlan_addr \
    vendor/onda/andy/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/onda/andy/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/onda/andy/proprietary/app/Stk.apk:system/app/Stk.apk \
    vendor/onda/andy/proprietary/app/Stksim2.apk:system/app/Stksim2.apk
